TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devTektronix_MSO_4104B.db
# FIXME -- HOW TO INSTALL Tektronix_MSO_4104B.proto????

#=======================================
include $(TOP)/configure/RULES
